
function getlegendname(l) {
switch (l) {
case "1":  return "Bödvar";
case "2":  return "Cassidy";
case "3":  return "Orion";
case "4":  return "Lord Vraxx";
case "5":  return "Gnash";
case "6":  return "Queen Nai";
case "7":  return "Hattori";
case "8":  return "Sir Roland";
case "9":  return "Scarlet";
case "10":  return "Thatch";
case "11":  return "Ada";
case "12":  return "Sentinel";
case "13":  return "Lucien";
case "14":  return "Teros";
case "15":  return "Brynn";
case "16":  return "Asuri";
case "17":  return "Barraza";
case "18":  return "Ember";
case "19":  return "Azoth";
case "20":  return "Koji";
case "21":  return "Ulgrim";
case "22":  return "Diana";
case "23":  return "Jhala";
case "24":  return "Kor";
case "25":  return "Wu Shang"; 
case "26":  return "Val"; 
case "27":  return "Ragnir";
case "28":  return "Cross";
case "29":  return "Mirage";
case "30":  return "Nix";
case "31":  return "Mordex";
case "32":  return "Yumiko";
case "33":  return "Artemis";
case "34":  return "Caspian";
case "35":  return "Sidra";
case "36":  return "Xull";
case "37":  return "Kaya";
case "38":  return "Isaiah";
case "39":  return "Jiro";
case "40":  return "Lin Fei";
case "41":  return "Zariel";
case "42":  return "Rayman";
case "43":  return "Dusk";
case "44":  return "Fait";
case "45":  return "Thor";
case "46":  return "Petra";
case "47":  return "Vector";
case "48":  return "Volkov";
case "49":  return "Onyx";
case "50":  return "Jaeyun";
case "51":  return "Mako";
case "52":  return "Magyar";
case "53":  return "Reno";
case "54":  return "Munin";
case "55":  return "Arcadia";
case "56":  return "Ezio";
case "57":  return "Tezca";
case "58":  return "Thea";
case "59":  return "Red Raptor";
case "60":  return "Loki";
case "61":  return "Seven";
case "62":  return "Vivi";
case "63":  return "Imugi"; 
case "64":  return "King Zuva"; 
case "65":  return "Priya";
case "66":  return "Ransom";
case "67":  return "Lady Vera";
case "68":  return "Rupture";
case "69":  return "Aurus"; 
case "70":  return "Qinghua & Baobao"; 
default: return "Unknown Legend";
}
}